config = {
    "stage_1_commands": {
        "N0": "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc -Zmir-opt-level=0 {file_path} -o {output}",
        "N1": "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc -Zmir-opt-level=1 {file_path} -o {output}",
        "N2": "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc -Zmir-opt-level=2 {file_path} -o {output}",
        "N3": "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc -Zmir-opt-level=3 {file_path} -o {output}",
        "N4": "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc -Zmir-opt-level=4 {file_path} -o {output}",
        # "OE": "./build/aarch64-apple-darwin/stage2/bin/rustc -Zexperimental-mir-optimizations {file_path} -o {output}",
        "O0": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=0 {file_path} -o {output}",
        "O1": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=1 {file_path} -o {output}",
        "O2": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=2 {file_path} -o {output}",
        "O3": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=3 {file_path} -o {output}",
        "Os": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=s {file_path} -o {output}",
        "Oz": "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc -C opt-level=z {file_path} -o {output}",
        "50": "/root/.rustup/toolchains/1.56.0-x86_64-unknown-linux-gnu/bin/rustc {file_path} -o {output}",
        # "O1": "rustc -C opt-level=1 {file_path} -o {output}",
        # "O2": "rustc -C opt-level=2 {file_path} -o {output}",
        # "O3": "rustc -C opt-level=3 {file_path} -o {output}",
        # "Os": "rustc -C opt-level=s {file_path} -o {output}",
        # "Oz": "rustc -C opt-level=z {file_path} -o {output}",
        # "M0": "arch -x86_64 /Users/mayank/Documents/mrustc/bin/mrustc -L /Users/mayank/Documents/mrustc/output {file_path} -o {output}",
        # "MO": "arch -x86_64 /Users/mayank/Documents/mrustc/bin/mrustc -O -L /Users/mayank/Documents/mrustc/output {file_path} -o {output}",
        # "C0": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=0 {file_path} -o {output}",
        # "C1": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=1 {file_path} -o {output}",
        # "C2": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=2 {file_path} -o {output}",
        # "C3": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=3 {file_path} -o {output}",
        # "Cs": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=s {file_path} -o {output}",
        # "Cz": "/Users/mayank/Downloads/build/rustc-clif -C opt-level=z {file_path} -o {output}",
        # "GO1": 'docker run --rm -v {folder_path}:/usr/src/myapp -w /usr/src/myapp philberty/gccrs:latest gccrs -g -O1 {file_name} -o {output}',
    }
}
